name: messier42_create_ann_and_apply_solution

services:
  activationBase:
    image: haaniansari/activationbase_messier42
    volumes:
      - type: bind
        source: ./ai_system
        target: /tmp/ai_system
    command: cp -r /tmp/activationBase /tmp/ai_system/

  knowledgeBase:
    image: droyyy/knowledgebase_messier42
    #also available at haaniansari/knowledgebase_messier42
    volumes:
      - type: bind
        source: ./ai_system
        target: /tmp/ai_system
    command: cp -r /tmp/knowledgeBase /tmp/ai_system/

  learningBase:
    image: haaniansari/learningbase_messier42
    #also available at droyyy/learningbase_messier42
    volumes:
      - type: bind
        source: ./ai_system
        target: /tmp/ai_system
    command: cp -r /tmp/learningBase /tmp/ai_system/

  codeBase:
    image: droyyy/codebase_messier42
    #also available at haaniansari/codebase_messier42
    volumes:
      - type: bind
        source: ./ai_system
        target: /tmp/ai_system
    command: bash -c "python3 /tmp/codeBase/ann_model/hybridModel.py && python3 /tmp/codeBase/editor.py" 

volumes:
  myvol:
